#!/bin/bash
set -e

# ASCII ART Generated by https://budavariam.github.io/asciiart-text/multi
echo -e "\033[0;32m"
cat <<'EOF'

                          888             d8b                           d8b                        888 
                          888             Y8P                           Y8P                        888 
                          888                                                                      888 
 .d8888b .d88b.  88888b.  888888  8888b.  888 88888b.   .d88b.  888d888 888 88888888  .d88b.   .d88888 
d88P"   d88""88b 888 "88b 888        "88b 888 888 "88b d8P  Y8b 888P"   888    d88P  d8P  Y8b d88" 888 
888     888  888 888  888 888    .d888888 888 888  888 88888888 888     888   d88P   88888888 888  888 
Y88b.   Y88..88P 888  888 Y88b.  888  888 888 888  888 Y8b.     888     888  d88P    Y8b.     Y88b 888 
 "Y8888P "Y88P"  888  888  "Y888 "Y888888 888 888  888  "Y8888  888     888 88888888  "Y8888   "Y88888 
                                                                                                       
                                                                                                       
                                                                                                       
 .d88888b.  8888888b.                    d8b                                                           
d88P" "Y88b 888  "Y88b                   Y8P                                                           
888     888 888    888                                                                                 
888     888 888    888  .d88b.  888  888 888  .d8888b .d88b.                                           
888     888 888    888 d8P  Y8b 888  888 888 d88P"   d8P  Y8b                                          
888 Y8b 888 888    888 88888888 Y88  88P 888 888     88888888                                          
Y88b.Y8b88P 888  .d88P Y8b.      Y8bd8P  888 Y88b.   Y8b.                                              
 "Y888888"  8888888P"   "Y8888    Y88P   888  "Y8888P "Y8888                                           
       Y8b                                                                                             
                                                                                                       
EOF

echo -e "\033[0m"

echo "IP-Address: $(hostname -I | awk '{print $1}')"

echo -e ""

# Initialize NSS-DB if not already present
if [ ! -f /etc/corosync/qnetd/nssdb/cert9.db ]; then
  echo "Initializing NSS database..."
  mkdir -p /etc/corosync/qnetd/nssdb
  chmod 700 /etc/corosync/qnetd/nssdb
  certutil -N -d sql:/etc/corosync/qnetd/nssdb --empty-password || {
    echo "Error initializing NSS database."
    exit 1
  }
else
  echo "NSS database already exists, skipping initialization."
fi

# Initialize authorized_keys if not already present
if [ ! -f ~/.ssh/authorized_keys ]; then
  echo "Initializing authorized_keys..."
  if [ -f ~/authorized_keys.old ]; then
    cp ~/authorized_keys.old ~/.ssh/authorized_keys
    chmod 700 ~/.ssh
    chmod 600 ~/.ssh/authorized_keys
  else
    echo "⚠️Warning⚠️: No authorized keys!"
  fi
else
  echo "authorized_keys already exists, skipping initialization."
fi

exec /usr/bin/supervisord -c /etc/supervisord.conf
